#!/bin/bash 

module load plgrid/tools/openmpi/common plgrid/libs/openblas/0.2.8 plgrid/tools/java8/oracle|| exit 1

max=$((UC_NODES * UC_PROCESSORS_PER_NODE))
num=1

chmod +x hpcc
for size in 23 25 27 
do
	bytes=`echo 2^$size | bc`
	bytes=$(( bytes * 8 ))
	megabytes=$(( (bytes + 1048575) / 1048576 ))
	megabytes=$(( 2 * megabytes ))
	while [ $num -le $max ]
	do
		echo Total=$megabytes > hpccmemf.txt
		mpirun -np $num ./hpcc
		
		echo $size > ra.config
		echo 60 >> ra.config
		mpiexec -np $num /bin/hostname -s | sort > nodes.txt
		mpiexec -np $num java -Dpcj.port=8099 -cp "./*" -Xms4g -Xmx4g pl.umk.mat.pcj.hpcc_randomaccess_java.RandomAccessNew
		
		num=$((num * 2))
	done
done

